/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#316a00",
        "on-error": "#450900",
        "on-tertiary": "#616300",
        "surface-container-low": "#101500",
        "secondary-fixed": "#d2ef6a",
        "surface-bright": "#263000",
        "tertiary-fixed": "#fbfe6b",
        "surface-container-high": "#1b2300",
        "error-dim": "#d53d18",
        "on-primary-fixed": "#204b00",
        "on-surface": "#f0fdbd",
        "outline-variant": "#424c1d",
        "on-background": "#f0fdbd",
        "on-primary": "#2b5f00",
        "primary-fixed-dim": "#94ee56",
        "on-secondary": "#485800",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed": "#374400",
        "on-tertiary-fixed": "#4d4e00",
        "surface-container-highest": "#202900",
        "on-secondary-fixed-variant": "#506200",
        "primary-fixed": "#a1fd63",
        "inverse-primary": "#326c00",
        "secondary-dim": "#c4e05e",
        "on-tertiary-fixed-variant": "#6a6c00",
        "error": "#ff7351",
        "background": "#0b1000",
        "inverse-on-surface": "#4f5a29",
        "tertiary": "#fdff9d",
        "inverse-surface": "#f4ffc6",
        "primary-container": "#5fb41f",
        "surface-tint": "#a1fd63",
        "surface-container": "#151c00",
        "secondary-container": "#536600",
        "tertiary-fixed-dim": "#ecef5f",
        "on-error-container": "#ffd2c8",
        "surface-dim": "#0b1000",
        "surface-variant": "#202900",
        "secondary-fixed-dim": "#c4e05e",
        "on-tertiary-container": "#585a00",
        "tertiary-container": "#eff261",
        "on-secondary-container": "#f0ffb7",
        "on-primary-container": "#0f2900",
        "on-surface-variant": "#a5b177",
        "secondary": "#d2ef6a",
        "outline": "#6f7a47",
        "surface": "#0b1000",
        "tertiary-dim": "#ecef5f",
        "error-container": "#b92902",
        "primary-dim": "#94ee56",
        "primary": "#a1fd63"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "base": "4px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "max-width": "1440px"
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        headline: ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
